### ISSUE TITLE
P0790 Effect of operator<=> on the C++ Standard Library

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#111]
[P0790R2](https://wg21.link/p0790r2) Effect of operator&lt;=&gt; on the C++ Standard Library (David Stone)

https://issues.isocpp.org/show_bug.cgi?id=355

**Comment by tituswinters** [comment]
Add support for the const_iterators, update the wording to reflect the vote on D1189. Forward to LWG for C++20.
SF F N A SA
5  4 3 0 0

**Comment by jensmaurer** [comment]
Integrated into [P1614](https://wg21.link/p1614) The Mothership Has Landed: Adding <=> to the Library #391.
