### ISSUE TITLE
P0891 Make strong_order a Customization Point!

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#122]
[P0891R2](https://wg21.link/p0891r2) Make strong_order a Customization Point! (Ga&#353;per A&#382;man, Jeff Snyder)

https://issues.isocpp.org/show_bug.cgi?id=503

Quote from paper: "R2 of this paper is a merge of its R1 and Jeff Snyder’s [P0863R1](https://wg21.link/p0863r1), and is synchronized with Barry Revzin’s" [P1186R1](https://wg21.link/p1186r1) #142.

**Comment by tituswinters** [comment]
We want to make strong_order (and friends) customization points (not strong_equals / weak_equals, those would be pessimizations, those APIs are removed).
SF F N A SA
2  8 1 0 1

We want the assume_ functions.
SF F N A SA
1  3 4 1 1

(Further discussion.)
We want the assume_ functions.
SF F N A SA
1  0 3 5 1

(Per discussion in P1188, we want a variation on the assume_ functions, and hope to forward that revision to LWG.)

**Comment by tituswinters** [comment]
We’re OK with the customization points.
strong_order, weak_order, etc are Neibloid customization points.
Unanimous consent

Rename the fallback functions, forward D0891R3 to LWG for C++20.
Unanimous consent

**Comment by jensmaurer** [comment]
Integrated into [P1614](https://wg21.link/p1614) The Mothership Has Landed: Adding <=> to the Library #391.
