### ISSUE TITLE
P1402 std::cstring_view - a C compatible std::string_view adapter

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#189]
[P1402R0](https://wg21.link/p1402r0) std::cstring_view - a C compatible std::string_view adapter (Andrew Tomazos)

**Comment by brycelelbach** [comment]
[Discussed at the Kona 2019 meeting by LEWGI](http://wiki.edg.com/bin/view/Wg21kona2019/P1402)

__Champion:__ Mike Spertus

__Minute Taker:__ Ben Craig

__Start Overview:__ 15:30

__Start Discussion:__ 15:40

__Start Polling:__ 15:52

__POLL: We should promise more committee time to pursuing a null-terminated string view, knowing that our time is scarce and this will leave less time for other work.__

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|0|4|4|4|3|

__Attendance:__ 16

__End:__ 16:00

__CONSENSUS: We will not pursue P1402R0 or this problem space.__
