### ISSUE TITLE
P1405 C++20 Executors are Resilient to ABI Breakage

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#192]
[P1405R0](https://wg21.link/p1405r0) C++20 Executors are Resilient to ABI Breakage (Jared Hoberock, Chris Kohlhoff)

Informational material for [P0443](https://wg21.link/p0443) A Unified Executors Proposal for C++ #102.

**Comment by tituswinters** [comment]
No action required, removing the LEWG label.
