### ISSUE TITLE
P1411 Please reconsider <scope> for C++20

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#196]
[P1411R0](https://wg21.link/p1411r0) Please reconsider &lt;scope&gt; for C++20 (Peter Sommerlad)

See also [P0052](https://wg21.link/p0052) Generic Scope Guard and RAII Wrapper for the Standard Library #278.

**Comment by PeterSommerlad** [comment]
uploaded d0052r10 to LWG wiki page and d1411r1 to LEWG wiki page both containing the wording for the proposed default constructor for unique_resource.

**Comment by tituswinters** [comment]
Discussed in LEWG, but P0052 will continue toward LFTS3.
