### ISSUE TITLE
P1440 is_clamped

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#210]
[P1440R0](https://wg21.link/p1440r0) is_clamped (Johel Guerrero)

**Comment by jensmaurer** [comment]
LEWG-I in Kona: No consensus to pursue.

**Comment by brycelelbach** [comment]
[Kona 2019-02 LEWGI Minutes](http://wiki.edg.com/bin/view/Wg21kona2019/P1440)

[P1440R0](https://wg21.link/P1440R0) std::is_clamped

__Champion:__ Bryce Adelstein Lelbach

__Minute Taker:__ Vincent Reverdy

__Start Overview:__ 16:15

__Start Polling:__ 16:23

__POLL: We should promise more committee time to pursuing [P1440R0](https://wg21.link/P1440R0), knowing that our time is scarce and this will leave less time for other work.__

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|0|0|3|5|5|

__Attendance:__ 15

__End:__ 16:30

__CONSENSUS: We will not pursue P1440R0 or this problem space.__
