### ISSUE TITLE
P1470 Against a standard concurrent hashmap

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#230]
[P1470R0](https://wg21.link/p1470r0) Against a standard concurrent hashmap (David Goldblatt)

**Comment by jensmaurer** [comment]
[SG1 in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1470R0-SG1)

**Comment by ogiroux** [comment]
Position paper, no further work expected.
