### ISSUE TITLE
P1471 The trouble with coroutine_traits

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#231]
[P1471R0](https://wg21.link/p1471r0) The trouble with coroutine_traits (Christopher Kohlhoff)

**Comment by jensmaurer** [comment]
[EWG in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1471R0-EWG)

**Comment by villevoutilainen** [comment]
Rejected by EWG in Kona 2019.
