### ISSUE TITLE
P1479 ostringstream wrapper

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#235]
[P1479R0](https://wg21.link/p1479r0) ostringstream wrapper (Robert Kawulak)

**Comment by brycelelbach** [comment]
[Discussed at the Kona 2019 meeting by LEWGI](http://wiki.edg.com/bin/view/Wg21kona2019/StringConcatenation)

[[https://wg21.link/P1479R0][P1479R0]] ostringstream wrapper

*Champion:* Mike Spertus

*Minute Taker:* Ben Craig

*Start Overview:* 16:00

*End:* 16:17

[[https://wg21.link/P1228R1][P1228R1]] std::concat

*Champion:* Jorg Brown

*Minute Taker:* Ben Craig

*Start Overview:* 16:17

*Start Polling:* 16:45

*POLL: We should promise more committee time to pursuing [[https://wg21.link/P1479R0][P1479R0]] ostringstream wrapper, knowing that our time is scarce and this will leave less time for other work.*
|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|0|1|8|6|1|
*Attendance:* 17

That has no consensus.

Peter Bindels (SA): Easy to do yourself, not sure it’s a good use of time.

*POLL: We should promise more committee time to pursuing [[https://wg21.link/P1228R1][P1228R1]] efficient string concatenation, knowing that our time is scarce and this will leave less time for other work.*
|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|2|9|3|2|0|
*Attendance:* 17

That has consensus.

Peter Bindels (A): Not sure this is a good fit for `std::`, use case may be too niche.

Bryce (A): Too many of these things; feel like fmt is good enough, and constexpr fmt may be a thing in the future.

*POLL: We want to see a revision of [[https://wg21.link/P1228R1][P1228R1]] that just concatenates things currently convertible to string_view and chars.*
|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|0|5|4|2|3|
*Attendance:* 15

That has no consensus.

*End:* 17:00

__CONSENSUS: We will not pursue P1479R0.__

__CONSENSUS: Bring a revision of P1228R1 to LEWGI for further design review.__
