### ISSUE TITLE
P1426 Pull the Plug on Contracts?

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#248]
[P1426R0](https://wg21.link/p1426r0) Pull the Plug on Contracts? (Nathan Myers)

**Comment by ncm** [comment]
Note that Hal posted an early draft of p1426 as the final version. The paper linked from the Wiki is (closer to) what I actually sent him to put in the mailing.

**Comment by jensmaurer** [comment]
[EWG in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1426R0-EWG).

**Comment by villevoutilainen** [comment]
Rejected in Kona 2019.
