### ISSUE TITLE
P1191 Adding operator<=> to types that are not currently comparable

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#266]
[P1191R0](https://wg21.link/p1191r0) Adding operator&lt;=&gt; to types that are not currently comparable (David Stone)

https://issues.isocpp.org/show_bug.cgi?id=527

**Comment by jensmaurer** [comment]
Titus Winters 2018-11-07 03:37:05 UTC
Discussed in San Diego: http://wiki.edg.com/bin/view/Wg21sandiego2018/P1191

Forward to LWG for C++20.
SF F N A SA
1 7 3 0 0

**Comment by mclow** [comment]
[P1191R0](https://wg21.link/p1191r0) has no proposed wording.

**Comment by jensmaurer** [comment]
Integrated into [P1614](https://wg21.link/p1614) The Mothership Has Landed: Adding <=> to the Library #391.
