### ISSUE TITLE
P1295 Spaceship library update

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#280]
[P1295R0](https://wg21.link/p1295r0) Spaceship library update (Tomasz Kami&#324;ski)

https://issues.isocpp.org/show_bug.cgi?id=551

**Comment by jensmaurer** [comment]
Titus Winters 2018-11-07 03:47:03 UTC
Discussed in San Diego: http://wiki.edg.com/bin/view/Wg21sandiego2018/P1295

Allow equality comparison for comparison_category.
SF F N A SA
4  6 1 0 0

Fix common_type to return the same result as common_comparison_category when common_comparison_category returns a result.
SF F N A SA
3  8 0 0 0

(Make sure to clarify that common_type and common_comparison_category differ in how they respond to comparison between incomparable types.)


Move compare_3way back into compare
SF F N A SA
2  5 3 0 0

Revise as above and forward to LWG for C++20.
Unanimous consent

**Comment by jensmaurer** [comment]
No update from author for 2019-02 Kona meeting.

**Comment by mclow** [comment]
No wording in paper. Not ready for LWG.

> 5. Proposed Wording
> TBD.

**Comment by jensmaurer** [comment]
Integrated into [P1614](https://wg21.link/p1614) The Mothership Has Landed: Adding <=> to the Library #391.
