### ISSUE TITLE
P0387 Memory Model Issues for Concurrent Data Structures

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#3]
[P0387R1](https://wg21.link/p0387r1) Memory Model Issues for Concurrent Data Structures (Hans-J. Boehm)

**Comment by jensmaurer** [comment]
[SG1 in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P0387R1-SG1)

**Comment by ogiroux** [comment]
Informational paper.
