### ISSUE TITLE
P1192 Experience report - integrating Executors with Parallel Algorithms

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#50]
[P1192R1](https://wg21.link/p1192r1) Experience report - integrating Executors with Parallel Algorithms (Thomas Rodgers)

**Comment by jensmaurer** [comment]
[SG1 in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1192R1-SG1)

**Comment by ogiroux** [comment]
Informational.
