### ISSUE TITLE
P1314 unique_val: a default-on-move type

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#66]
[P1314R1](https://wg21.link/p1314r1) unique_val: a default-on-move type (Miguel Ojeda)

**Comment by jensmaurer** [comment]
Discussion on lib-ext: http://lists.isocpp.org/lib-ext/2018/12/9459.php

**Comment by brycelelbach** [comment]
[Discussed at the Kona 2019 meeting in LEWGI](http://wiki.edg.com/bin/view/Wg21kona2019/P1314)

__Champion:__ Bryce Adelstein Lelbach

__Minute Taker:__ Billy Baker

__Start Overview:__ 10:10

__Start Polling:__ 10:20

__POLL: We should promise more committee time to [[https://wg21.link/P1314R1][P1314R1]], knowing that our time is scarce and this will leave less time for other work.__

__NO OBJECTION TO UNANIMOUS DISSENT__

__Attendance:__ 11

__End:__ 10:21

__CONSENSUS: We will not pursue P1314R0.__
