### ISSUE TITLE
P1349 Better Integration of Sender Executors

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#78]
[P1349R0](https://wg21.link/p1349r0) Better Integration of Sender Executors (Vinnie Falco)

**Comment by jensmaurer** [comment]
[SG1 in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1349R0-SG1)

**Comment by ogiroux** [comment]
SG1 result: Raises concerns about Senders. Authors are working on related issues, and this should be reflected in the next revision of that paper. Keeping SG1 tag.

**Comment by ogiroux** [comment]
But this paper is a position paper and expect no further work.
