### ISSUE TITLE
P1372 Giving atomic_ref implementers more flexibility by providing customization points for non-lock-free implementation

### ISSUE THREAD

**Issue by jensmaurer** [jensmaurer/papers#88]
[P1372R0](https://wg21.link/p1372r0) Giving atomic_ref implementers more flexibility by providing customization points for non-lock-free implementation (David S. Hollman)

**Comment by jensmaurer** [comment]
[SG1 in Kona](http://wiki.edg.com/bin/view/Wg21kona2019/P1372R0-SG1)

**Comment by ogiroux** [comment]
SG1 poll:
"We believe that it should be possible to customize the behavior of atomic_ref<T>
when atomic_ref<T>::is_always_lock_free is false."
SF  F  N   A  SA
0   3  14  2  0

This paper is possibly done.
